- name: Setup dotfiles
  hosts: localhost
  become_user: "{{ ansible_user_id }}"
  tasks:
    - name: clone dotfiles repository
      git: repo=https://github.com/briancw/dotfiles.git
           dest={{ ansible_user_dir }}/.dotfiles
           update=no

    - name: zshrc symlink
      file: path={{ ansible_user_dir }}/.zshrc
            src={{ ansible_user_dir }}/.dotfiles/zsh/.zshrc
            state=link

    - name: zshenv symlink
      file: path={{ ansible_user_dir }}/.zshenv
            src={{ ansible_user_dir }}/.dotfiles/zsh/.zshenv
            state=link

    - name: aliases symlink
      file: path={{ ansible_user_dir }}/.aliases
            src={{ ansible_user_dir }}/.dotfiles/zsh/.aliases
            state=link            

    - name: npmrc symlink
      file: path={{ ansible_user_dir }}/.npmrc
            src={{ ansible_user_dir }}/.dotfiles/npm/.npmrc
            state=link

    - name: gitconfig symlink
      file: path={{ ansible_user_dir }}/.gitconfig
            src={{ ansible_user_dir }}/.dotfiles/git/.gitconfig
            state=link

    - name: gitignore symlink
      file: path={{ ansible_user_dir }}/.gitignore_global
            src={{ ansible_user_dir }}/.dotfiles/git/.gitignore_global
            state=link